# Site
name: "Snapsec | blog"
title: "Snapsec | Blog"
description: "Snapsec - A cybersecurity Company."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /blog
google_analytics: 'UA-208550451-1'
disqus: 'snapsec-co'
mailchimp-list: 'https://snapsec.us14.list-manage.com/subscribe/post?u=50c67e68d53e5d91fa87f8496&amp;id=c4ebf52467'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  imran:
    name: imran
    display_name: "Imran Parray"
    gravatar: c733af153b37e924248ed05898786474
    email: parrayimran5@gmail.com
    web: https://imran-parray.github.io/blog
    twitter: https://twitter.com/imranparray101
    description: "CEO | Founder @snapsec "
  ab:
    name: "Abdul Basit"
    display_name: "Abdul Basit"    
    gravatar: 406f10d9c3f635060b2129861f1b5c54
    email: peerzadaabdulbasit120@gmail.com
    web: https://twitter.com/PeerzadaBasit
    twitter: https://twitter.com/Peerzadaabdulb2
    description: "Peerzada abdul basit is an Appsec Engineer at snapsec."
  mubashir:
    name: "Mubashir Paray"
    display_name: "Mubashir Paray"    
    gravatar: 0e3a0093693366e9374745064c0adb25
    email: mubashirmehraj789@gmail.com
    web: https://twitter.com/mubashirparay7
    twitter: https://twitter.com/mubashirparay7
    description: "Mubashir Paray is an Appsec Engineer at snapsec, He likes to talk about security, mental health and personal development."
  adnan:
    name: "Adnan Shah"
    display_name: "Adnan Shah"    
    gravatar: 520c2e06e1caf97dbc4f98f913ec47f1
    email: adnanhaq30@gmail.com
    web: https://twitter.com/adnan_shah__
    twitter: https://twitter.com/adnan_shah__
    description: "Adnan Shah is an Appsec Engineer and a passionate adventurer."
  danish:
    name: "Danish Bhat"
    display_name: "Danish Bhat"    
    gravatar: 728f98f86c605a9c42434a342dc9489b
    email: bhatdanish627@gmail.com
    web: https://twitter.com/DanishB23511699
    twitter: https://twitter.com/DanishB23511699
    description: "Danish Bhat is an Appsec Engineer at snapsec, He is likes to talk about websec, Api security and Linux."
  waseem:
    name: "Waseem Lone"
    display_name: "Waseem Lone"    
    gravatar: 9c1d8922bbc2ec710f8482c71523e25c
    email: loneamir283@gmail.com
    web: https://twitter.com/WaseemR86269739
    twitter: https://twitter.com/WaseemR86269739
    description: "Building and Breaking."
    
    
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
